"""add category_id to annual_envelopes

Revision ID: 067d190a6426
Revises: 4d7ce2673b79
Create Date: 2026-03-30 22:41:53.030344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067d190a6426'
down_revision: Union[str, Sequence[str], None] = '4d7ce2673b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_envelopes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_envelope_category', 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_envelopes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_envelope_category', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
