"""add split_rules table

Revision ID: 25066d223828
Revises: 7a5cb3d1f00f
Create Date: 2026-04-03 18:40:56.489167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25066d223828'
down_revision: Union[str, Sequence[str], None] = '7a5cb3d1f00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('split_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=200), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('splits', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('split_rules')
    # ### end Alembic commands ###
