"""add initial_balance to envelopes

Revision ID: 383ef9417664
Revises: 067d190a6426
Create Date: 2026-03-30 23:08:04.815511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383ef9417664'
down_revision: Union[str, Sequence[str], None] = '067d190a6426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_envelopes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_balance', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_envelopes', schema=None) as batch_op:
        batch_op.drop_column('initial_balance')

    # ### end Alembic commands ###
