"""fix nullable columns

Revision ID: 4d7ce2673b79
Revises: 3f4e1add013d
Create Date: 2026-03-29 18:35:34.917254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7ce2673b79'
down_revision: Union[str, Sequence[str], None] = '3f4e1add013d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('value_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('value_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
